---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: demo-app
  name: demo-app
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: demo-app
---
